-- AlterTable
ALTER TABLE "chunk_subtitles" ALTER COLUMN "start" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "end" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "raw_subtitles" ALTER COLUMN "start" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "end" SET DATA TYPE DOUBLE PRECISION;
